### PR TITLE
Fix memory leak in ConnectActivity when autofill is not used

### LINKED ISSUE #145: Memory leak in webview/ConnectActivity when otp autofill doesn't get used
```
E/ActivityThread: Activity com.telenor.connect.ui.ConnectActivity has leaked IntentReceiver com.telenor.connect.sms.SmsBroadcastReceiver@e8c5823 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.telenor.connect.ui.ConnectActivity has leaked IntentReceiver com.telenor.connect.sms.SmsBroadcastReceiver@e8c5823 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1355)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1120)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1428)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1401)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1389)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:622)
        at com.telenor.connect.ui.ConnectWebViewClient.<init>(ConnectWebViewClient.java:67)
        at com.telenor.connect.ui.ConnectWebFragment.onCreateView(ConnectWebFragment.java:64)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
        at android.app.Activity.performStart(Activity.java:7200)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2918)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

### PR DESCRIPTION
**Pull request by jorunfa**

### CODE REVIEW

File: connect/src/com/telenor/connect/ui/ConnectActivity.java [hunk 1]
```diff
@@ -17,12 +19,17 @@
 import com.telenor.connect.utils.ConnectUrlHelper;
 import com.telenor.connect.utils.ConnectUtils;
 
+import java.util.HashSet;
+import java.util.Iterator;
```
Comment (froeseth) [inline connect/src/com/telenor/connect/ui/ConnectActivity.java]: I can't immeadiately tell where the Iterator and List imports are being used. Remove in case they're not used in this class.

Comment (jorunfa) [reply connect/src/com/telenor/connect/ui/ConnectActivity.java]: Ah, thanks. Refactored the implementation, but forgot to remove these.

Comment (jorunfa) [reply connect/src/com/telenor/connect/ui/ConnectActivity.java]: Resolved by ae4ca8b
